import Head from "next/head";
import HeaderSection from "../component/layout/header";
import "../styles/globals.css";
import styled from "@emotion/styled";

function MyApp({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Lucy&apos;s Log</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <HeaderSection />

        <Component {...pageProps} />
      </Container>
    </>
  );
}

export default MyApp;
const Container = styled.div`
  width: 80%;
  max-width: 950px;
  margin: auto;
  min-height: 100vh !important;
`;
